server:
  port: 8083
spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      routes:
        -id: ms1
        uri: http://localhost:8081
        predicates:
          - Path=/ms1/**
        filters:
          - PrefixPath=/api

